import {Platform} from 'react-native';
import {getStatusBarHeight, ifIphoneX} from 'react-native-iphone-x-helper';
import {colors} from './colors';
import {ScaledSheet} from 'react-native-size-matters';
export const globalStyles = ScaledSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.bg,
    ...Platform.select({
      ios: {
        // paddingTop: getStatusBarHeight() - 15,
        ...ifIphoneX(
          {paddingTop: getStatusBarHeight() - 15},
          {paddingTop: getStatusBarHeight()},
        ),
      },
      android: {paddingTop: getStatusBarHeight()},
    }),
  },
  weatherImage: {
    width: '100@ms',
    height: '100@ms',
  },
  // Flex
  flexCenter: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  flexRow: {
    flexDirection: 'row',
  },
  alignItemsCenter: {
    alignItems: 'center',
  },
  justifyBetween: {
    justifyContent: 'space-between',
  },
  pt0: {paddingTop: 0},
  pt1: {paddingTop: 10},
  pt2: {paddingTop: 20},
  pt3: {paddingTop: 30},
  pt4: {paddingTop: 40},
  pt5: {paddingTop: 50},

  pb0: {paddingBottom: 0},
  pb1: {paddingBottom: 10},
  pb2: {paddingBottom: 20},
  pb3: {paddingBottom: 30},
  pb4: {paddingBottom: 40},
  pb5: {paddingBottom: 50},

  pl0: {paddingLeft: 0},
  pl1: {paddingLeft: 10},
  pl2: {paddingLeft: 20},
  pl3: {paddingLeft: 30},
  pl4: {paddingLeft: 40},
  pl5: {paddingLeft: 50},

  pr0: {paddingRight: 0},
  pr1: {paddingRight: 10},
  pr2: {paddingRight: 20},
  pr3: {paddingRight: 30},
  pr4: {paddingRight: 40},
  pr5: {paddingRight: 50},

  px0: {paddingHorizontal: 0},
  px1: {paddingHorizontal: 10},
  px2: {paddingHorizontal: 20},
  px3: {paddingHorizontal: 30},
  px4: {paddingHorizontal: 40},
  px5: {paddingHorizontal: 50},

  py0: {paddingVertical: 0},
  py1: {paddingVertical: 10},
  py2: {paddingVertical: 20},
  py3: {paddingVertical: 30},
  py4: {paddingVertical: 40},
  py5: {paddingVertical: 50},

  mt1: {marginTop: 10},
  mt2: {marginTop: 20},
  mt3: {marginTop: 30},
  mt4: {marginTop: 40},
  mt5: {marginTop: 50},
  mt7: {marginTop: 70},

  mb1: {marginBottom: 10},
  mb2: {marginBottom: 20},
  mb3: {marginBottom: 30},
  mb4: {marginBottom: 40},
  mb5: {marginBottom: 50},

  ml0: {marginLeft: 0},
  ml1: {marginLeft: 10},
  ml2: {marginLeft: 20},
  ml3: {marginLeft: 30},
  ml4: {marginLeft: 40},
  ml5: {marginLeft: 50},

  mr0: {marginRight: 0},
  mr1: {marginRight: 10},
  mr2: {marginRight: 20},
  mr3: {marginRight: 30},
  mr4: {marginRight: 40},
  mr5: {marginRight: 50},

  mx0: {marginHorizontal: 0},
  mx1: {marginHorizontal: 10},
  mx2: {marginHorizontal: 20},
  mx3: {marginHorizontal: 30},
  mx4: {marginHorizontal: 40},
  mx5: {marginHorizontal: 50},

  my0: {marginVertical: 0},
  my1: {marginVertical: 10},
  my2: {marginVertical: 20},
  my3: {marginVertical: 30},
  my4: {marginVertical: 40},
  my5: {marginVertical: 50},
  w1: {width: '10%'},
  w2: {width: '20%'},
  w2p5: {width: '25%'},
  w3: {width: '30%'},
  w4: {width: '40%'},
  w4p5: {width: '45%'},
  w5: {width: '50%'},
  w6: {width: '60%'},
  w7: {width: '70%'},
  w8: {width: '80%'},
  w9: {width: '90%'},
  w10: {width: '100%'},
  h1: {height: '10%'},
  h2: {height: '20%'},
  h3: {height: '30%'},
  h4: {height: '40%'},
  h5: {height: '50%'},
  h6: {height: '60%'},
  h7: {height: '70%'},
  h8: {height: '80%'},
  h9: {height: '90%'},
  h10: {height: '100%'},
});
